version: '3'
services:
  visualizador:
    image: dockersamples/visualizer
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
    - 9080:8080
    deploy:
      placement:
        constraints:
          - node.role == manager

  api:
    image: anderson0000/spring-api
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - net
    ports:
      - 8080:8080

networks:
  net:
    external: true